<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TNR Activité Choix, Swap, Recup seulement</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>3</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>0c4956dd-97ce-456d-88fe-de3d183f3200</testSuiteGuid>
   <testCaseLink>
      <guid>aca313d9-963c-4a8a-993e-a76b470b6a05</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/03-Activité choix de numéro/03-Choix numéro sans sortie SIM</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0cb78a46-fc0b-4cf7-a262-fd222fae08d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>80eb39c6-db45-45ab-804d-6f6dbc8b1e08</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>75ffef15-3383-4afc-84c7-d9d74f86cbdc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/03-Activité choix de numéro/05-Choix numéro avec sortie SIM</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cb87d9c3-5299-47de-8e13-06e7088901ce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83d1dd1a-460d-4304-9c1b-5dd7947d5f4c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d705fc39-6a78-4165-bb06-acc26cb0002f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/05-Activité SIM Swap/03-SIM Swap sans sortie SIM</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>879fb405-88cd-49e6-b111-36680c2df3e3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d0eb708a-8d0b-4a25-957b-5a1f272a5d8a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>400eef62-800a-49f7-b03c-21234a2df86f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/05-Activité SIM Swap/02-SIM Swap avec un ICCID invalide</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>ce038ac2-7738-4052-bf9a-f102e02d0b96</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/04-Activité récupération numéro/03-Récupération numéro sans sortie SIM</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b4b3868-e48b-4f61-95f8-f18a71c2b140</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dcbe53d9-a701-4fec-b68a-64603eceb157</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cde73e99-705d-4317-946a-dd3ec0054335</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/04-Activité récupération numéro/05-Récupération numéro avec sortie SIM</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b51e109c-12fa-4d80-95dc-1c1660296bce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4008e60a-43eb-444c-ad33-59e1ea6e9a96</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8f793894-6743-44a2-956a-6b7854074e55</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/03-Activité choix de numéro/04-Vérification opération choix numéro sans sortie SIM</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f6df6b74-e061-424d-a1b1-2f8a52e1a659</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f2c0ce6-2379-4baf-bea0-c66a0070026f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>07077598-d686-4060-ac68-8e9280724828</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/03-Activité choix de numéro/06-Vérification opération choix numéro avec sortie SIM</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>87268653-696f-4ac8-8066-0db113ba4f01</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2fddc8ea-91d9-434c-b6f3-2230f993be33</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2244b952-20e3-47f4-b1fd-1287b9603d27</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/05-Activité SIM Swap/04-Vérification opération SIM Swap sans sortie SIM</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c04e8b0b-a232-4f21-81de-14b05b57cb6d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3e111d53-4f62-486d-a510-8edee8e140b6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1358fa82-81f6-4ff2-8b1e-6164e06323fc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/05-Activité SIM Swap/06-Vérification opération SIM Swap avec sortie SIM</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a6f8896-7dd8-4586-af71-fb030dc0e01d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>44e4a3b1-092a-46fd-b1c8-0c1a6f2f942c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a7c082ce-a188-4beb-abf7-53a9428dad80</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/04-Activité récupération numéro/04-Vérification opération Recuperation numéro sans sortie SIM</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>999f49a2-be22-4792-87ef-e6948ee4bbac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>549c5aaa-fe9f-4641-99dd-405039deb24c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b17512b1-32d9-456d-9d90-6af7f8438c26</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/04-Activité récupération numéro/06-Vérification opération Recuperation numéro avec sortie SIM</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ea264bb-0626-4f4a-b266-2cd9bf8a2bf4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85d587bf-6ee7-4de1-b5d2-2e073df226f5</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
